import React, { useEffect, useMemo, useRef, useState } from 'react';

type Round={a:string;b:string;options:string[];answer:number};
type Packet={type:'hello'|'pick'|'start';name?:string;pick?:number;round?:number};
const BANK:Round[]=[
{a:'Se derrite al sol',b:'Puede ser de chocolate',options:['Nube','Helado','Piedra','Café'],answer:1},
{a:'Tiene páginas',b:'Puede llevarte a otros mundos',options:['Libro','Espejo','Zapato','Reloj'],answer:0},
{a:'Cae del cielo',b:'Deja las calles brillantes',options:['Lluvia','Arena','Humo','Nieve'],answer:0},
{a:'Tiene agujas',b:'Te dice cuándo',options:['Árbol','Reloj','Guitarra','Mapa'],answer:1},
{a:'Vive en el mar',b:'Tiene ocho brazos',options:['Delfín','Pulpo','Tiburón','Pingüino'],answer:1},
{a:'Se enciende de noche',b:'Está en el cielo',options:['Luna','Montaña','Puerta','Río'],answer:0},
{a:'Tiene ruedas',b:'Te lleva por carretera',options:['Bicicleta','Coche','Barco','Avión'],answer:1},
{a:'Es amarillo',b:'Tiene forma de fruta',options:['Plátano','Cereza','Uva','Kiwi'],answer:0},
{a:'Tiene teclas',b:'Puede hacer música',options:['Piano','Cuchara','Ventana','Mochila'],answer:0},
{a:'Se abre con llave',b:'Protege una habitación',options:['Puerta','Alfombra','Silla','Vela'],answer:0}];
const NAMES=['Luna','Rayo','Nube','Pixel','Coco','Menta','Kiwi','Chispa'];
const pad=(n:number)=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`};
const daily=()=>{const s=[...today()].reduce((a,c)=>a+c.charCodeAt(0),0);return Array.from({length:5},(_,i)=>BANK[(s+i*7)%BANK.length])};
const Peer=(window as any).Peer;

export default function App(){
 const rounds=useMemo(daily,[]); const [screen,setScreen]=useState<'home'|'game'|'done'>('home'); const [mode,setMode]=useState<'solo'|'online'>('solo');
 const [name,setName]=useState(localStorage.getItem('dp-name')||NAMES[Math.floor(Math.random()*NAMES.length)]); const [room,setRoom]=useState(''); const [roomInput,setRoomInput]=useState(''); const [status,setStatus]=useState(''); const [friend,setFriend]=useState('');
 const [round,setRound]=useState(0); const [pick,setPick]=useState<number|null>(null); const [friendPick,setFriendPick]=useState<number|null>(null); const [score,setScore]=useState(0); const [seconds,setSeconds]=useState(60); const [result,setResult]=useState<string|null>(null); const [connected,setConnected]=useState(false);
 const peer=useRef<any>(null); const conn=useRef<any>(null); const timer=useRef<number|null>(null);
 useEffect(()=>localStorage.setItem('dp-name',name),[name]); useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);peer.current?.destroy?.()},[]);
 const send=(p:Packet)=>{if(conn.current?.open)conn.current.send(p)};
 const attach=(c:any)=>{conn.current=c;c.on('open',()=>{setConnected(true);setStatus('Conectados.');c.send({type:'hello',name})});c.on('data',(p:Packet)=>{if(p.type==='hello')setFriend(p.name||'Amigo');if(p.type==='pick')setFriendPick(p.pick??null);if(p.type==='start'){setMode('online');setRound(0);setPick(null);setFriendPick(null);setScore(0);setSeconds(60);setResult(null);setScreen('game')}});c.on('close',()=>setConnected(false))};
 const create=()=>{if(!Peer)return setStatus('Modo online no disponible.');const id=Math.random().toString(36).slice(2,7).toUpperCase();setRoom(id);setMode('online');const p=new Peer(`doblepulso-${id.toLowerCase()}`);peer.current=p;setStatus('Creando sala…');p.on('open',()=>setStatus(`Sala ${id} lista. Comparte el código.`));p.on('connection',attach);p.on('error',()=>setStatus('No se pudo crear la sala.'))};
 const join=()=>{if(!Peer)return;const id=roomInput.trim().toUpperCase();if(id.length!==5)return setStatus('El código tiene 5 caracteres.');const p=new Peer();peer.current=p;p.on('open',()=>{const c=p.connect(`doblepulso-${id.toLowerCase()}`);attach(c);setRoom(id);setMode('online');setStatus('Buscando a tu amigo…')});p.on('error',()=>setStatus('No encontramos esa sala.'))};
 const start=(online=false)=>{setMode(online?'online':'solo');setRound(0);setPick(null);setFriendPick(null);setScore(0);setSeconds(60);setResult(null);setScreen('game');if(online)send({type:'start'})};
 useEffect(()=>{if(screen!=='game')return;timer.current=window.setInterval(()=>setSeconds(s=>{if(s<=1){if(timer.current)clearInterval(timer.current);setScreen('done');return 0}return s-1}),1000);return()=>{if(timer.current)clearInterval(timer.current)}},[screen]);
 const resolve=(a:number,b:number)=>{const ok=rounds[round].answer;const perfect=a===ok&&b===ok;const good=a===ok||b===ok;setResult(perfect?'⚡ ¡Pulso perfecto! +2':good?'✨ Uno de los dos lo clavó. +1':'💨 No hubo eco.');setScore(s=>s+(perfect?2:good?1:0));window.setTimeout(()=>{if(round===4){setScreen('done');return}setRound(r=>r+1);setPick(null);setFriendPick(null);setResult(null)},850)};
 useEffect(()=>{if(mode==='online'&&pick!==null&&friendPick!==null&&!result)resolve(pick,friendPick)},[pick,friendPick]);
 const choose=(i:number)=>{if(pick!==null||result)return;setPick(i);send({type:'pick',pick:i,round});if(mode==='solo')resolve(i,i);else if(friendPick!==null)resolve(i,friendPick)};
 if(screen==='done')return <main className="page"><section className="card result"><div className="eyebrow">PULSO DEL DÍA · {today()}</div><div className="bigScore">{score}<span>/10</span></div><h1>{score>=8?'Tenéis telepatía.':'Buen pulso.'}</h1><p>{score>=8?'Dos mentes, una respuesta.':'Mañana hay otro reto. Vuelve con alguien.'}</p><div className="resultGrid"><div><b>{score>=8?'🔥':'✨'}</b><small>resultado</small></div><div><b>{mode==='solo'?'Solo':connected?'En equipo':'Amigo'}</b><small>modo</small></div></div><button className="primary" onClick={()=>setScreen('home')}>Volver al inicio</button></section></main>;
 if(screen==='game'){const r=rounds[round];return <main className="page gamePage"><header className="top"><button className="logo" onClick={()=>setScreen('home')}>DP</button><div className="progress"><span>RONDA {round+1}/5</span><div><i style={{width:`${round*25}%`}}/></div></div><div className="clock">00:{pad(seconds)}</div></header><section className="gameCard"><div className="clues"><div><small>PISTA A</small><strong>{r.a}</strong></div><div><small>PISTA B</small><strong>{r.b}</strong></div></div><p className="question">Elegid el mismo concepto.</p><div className="options">{r.options.map((o,i)=><button key={o} className={pick===i?'picked':''} disabled={pick!==null||!!result} onClick={()=>choose(i)}>{o}<span>{String.fromCharCode(65+i)}</span></button>)}</div>{result&&<div className="roundResult">{result}</div>}<div className="teamState"><span className={`dot ${mode==='solo'||connected?'on':''}`}/>{mode==='solo'?'Modo práctica':connected?`${friend||'Amigo'} conectado`:'Esperando a tu amigo…'}{friendPick!==null&&<em> · ya ha elegido</em>}</div></section></main>}
 return <main className="page"><section className="hero"><div className="eyebrow">UN JUEGO DIARIO · 60 SEGUNDOS</div><h1>DOBLE<br/><em>PULSO</em></h1><p>Un acertijo. Dos mentes. Una sola respuesta.<br/>Vuelve mañana para otro.</p><div className="date">● RETO DE HOY · {today()}</div></section><section className="homeCard"><label>¿Cómo te llamas?</label><input value={name} maxLength={14} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={()=>start(false)}>Jugar solo <span>→</span></button><div className="or"><i/> o juega con un amigo <i/></div><div className="online"><button className="secondary" onClick={create}>Crear sala</button><div className="join"><input placeholder="CÓDIGO" maxLength={5} value={roomInput} onChange={e=>setRoomInput(e.target.value.toUpperCase())}/><button onClick={join}>Unirse</button></div></div>{room&&<div className="room"><b>{room}</b><span>{connected?'Conectado':'Comparte este código'}</span><button disabled={!connected} onClick={()=>start(true)}>Empezar →</button></div>}{status&&<p className="status">{status}</p>}<small className="note">Sin registro · móvil · una partida rápida al día</small></section></main>;
}
